#!/usr/bin/env node

import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

import result from "./basedef.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const outputPath = join(__dirname, "index.ts");

const output = `// Auto-generated by build-base.ts - DO NOT EDIT MANUALLY
import type { tsAllKW } from "./basedef.js";

export type tsPrimitiveType = ${result.primitiveTypes.map(s=>`"${s}"`).join(" | ")};

type tsDNAHelperBase = {
  constraint:string[];
  container:string[];
  constraintsForObject: string[];
  containerArrayKeys: string[];
  containerObjectKeys: string[];
  modifier: string[];
  nonActionable: string[];
  priority0: string[];
  priority1: string[];
  valueArrayKeys: string[];
  wrapper: string[];
};

export type tsDNAHelper = tsDNAHelperBase & {
  refType: { [k: string]: tsPrimitiveType };
  primitiveType: tsPrimitiveType[];
};

const _default = ${JSON.stringify(result, null, 2)} as unknown as tsDNAHelper;

const allkeywords = ${JSON.stringify(result, null, 2)} as tsAllKW;

// Category bits from helpers
const c = ${JSON.stringify(classifiers.dic, null, 2)};
const mc = ${JSON.stringify(metaClassifiers.dic, null, 2)};

export function getCategory(keyword: string): "typeDecl" | "constraint" | "wrapper" | "container" | "root" {
  if (!keyword) return "root";
  const entry = allkeywords[keyword];
  if (!entry) return "root";
  const classifiers = entry[1];
  if (classifiers & c.typeDecl) return "typeDecl";
  if (classifiers & c.constraint) return "constraint";
  if (classifiers & c.wrapper) return "wrapper";
  if (classifiers & mc.container) return "container";
  return "root";
}




export default _default;
`

writeFileSync(outputPath, output, "utf-8");
console.log(`Generated ${outputPath}`);
