// Auto-generated by build-base.ts - DO NOT EDIT MANUALLY
// import type { tsAllKW } from "./basedef.js";

export type tsPrimitiveType = "any" | "string" | "boolean" | "null" | "integer" | "bigint" | "number" | "array" | "object";

type tsDNAHelperBase = {
  constraint:string[];
  container:string[];
  constraintsForObject: string[];
  containerArrayKeys: string[];
  containerObjectKeys: string[];
  modifier: string[];
  nonActionable: string[];
  priority0: string[];
  priority1: string[];
  valueArrayKeys: string[];
  wrapper: string[];
};

export type tsDNAHelper = tsDNAHelperBase & {
  refType: { [k: string]: tsPrimitiveType };
  primitiveType: tsPrimitiveType[];
};


export default {
  "constraintsForObject": [
    "properties",
    "patternProperties",
    "additionalProperties",
    "unevaluatedProperties",
    "propertyNames",
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "dependentSchemas",
    "$defs",
    "definitions"
  ],
  "constraint": [
    "minLength",
    "maxLength",
    "pattern",
    "format",
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum",
    "multipleOf",
    "uniqueItems",
    "minContains",
    "maxContains",
    "minItems",
    "maxItems"
  ],
  "container": [
    "enum",
    "prefixItems",
    "properties",
    "patternProperties",
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "dependentSchemas",
    "allOf",
    "anyOf",
    "oneOf",
    "$defs",
    "definitions",
    "examples"
  ],
  "containerArrayKeys": [
    "enum",
    "prefixItems",
    "properties",
    "patternProperties",
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "dependentSchemas",
    "allOf",
    "anyOf",
    "oneOf",
    "$defs",
    "definitions",
    "examples"
  ],
  "containerObjectKeys": [
    "enum",
    "prefixItems",
    "properties",
    "patternProperties",
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "dependentSchemas",
    "allOf",
    "anyOf",
    "oneOf",
    "$defs",
    "definitions",
    "examples"
  ],
  "modifier": [
    "exclusiveMinimum",
    "exclusiveMaximum"
  ],
  "nonActionable": [
    "title",
    "description",
    "examples",
    "$comment"
  ],
  "priority0": [
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "dependentSchemas"
  ],
  "priority1": [
    "properties",
    "patternProperties",
    "additionalProperties",
    "unevaluatedProperties",
    "propertyNames"
  ],
  "typeDecl": [
    "type",
    "enum",
    "const"
  ],
  "valueArrayKeys": [
    "type",
    "enum",
    "const",
    "minLength",
    "maxLength",
    "pattern",
    "format",
    "minimum",
    "maximum",
    "exclusiveMinimum",
    "exclusiveMaximum",
    "multipleOf",
    "uniqueItems",
    "minContains",
    "maxContains",
    "minItems",
    "maxItems",
    "required",
    "minProperties",
    "maxProperties",
    "dependentRequired",
    "$ref",
    "$anchor",
    "$dynamicRef",
    "$dynamicAnchor",
    "$id",
    "$schema",
    "title",
    "description",
    "default",
    "examples",
    "$comment"
  ],
  "wrapper": [
    "not",
    "if",
    "then",
    "else",
    "default"
  ],
  "refType": {
    "type": "any",
    "enum": "any",
    "const": "any",
    "minLength": "string",
    "maxLength": "string",
    "pattern": "string",
    "format": "string",
    "minimum": "number",
    "maximum": "number",
    "exclusiveMinimum": "number",
    "exclusiveMaximum": "number",
    "multipleOf": "number",
    "prefixItems": "array",
    "items": "array",
    "additionalItems": "array",
    "uniqueItems": "array",
    "contains": "array",
    "minContains": "array",
    "maxContains": "array",
    "minItems": "array",
    "maxItems": "array",
    "unevaluatedItems": "array",
    "properties": "object",
    "patternProperties": "object",
    "additionalProperties": "object",
    "unevaluatedProperties": "object",
    "propertyNames": "object",
    "required": "object",
    "minProperties": "object",
    "maxProperties": "object",
    "dependentRequired": "object",
    "dependentSchemas": "object",
    "allOf": "any",
    "anyOf": "any",
    "oneOf": "any",
    "not": "any",
    "if": "any",
    "then": "any",
    "else": "any",
    "$ref": "any",
    "$anchor": "any",
    "$dynamicRef": "any",
    "$dynamicAnchor": "any",
    "$id": "any",
    "$schema": "any",
    "$defs": "object",
    "definitions": "object",
    "title": "any",
    "description": "any",
    "default": "any",
    "examples": "any",
    "$comment": "any"
  },
  "primitiveTypes": [
    "any",
    "string",
    "boolean",
    "null",
    "integer",
    "bigint",
    "number",
    "array",
    "object"
  ]
} as unknown as tsDNAHelper