version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Root monorepo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/shared" # Internal shared toolbox
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/query-builder"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/wf-runner"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/dna"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/schvalid"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
