changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - octocat
  categories:
    - title: "Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
    - title: "Maintenance & Misc"
      labels:
        - chore
        - documentation
        - dependencies
