-- Governance MCP schema (generated by @ytrynot/gov-mcp)
-- All tables and indexes generated by @ytrynot/qb (CHECK constraints via column-level check)
CREATE TABLE IF NOT EXISTS scopes (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  description TEXT,
  parent TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (parent) REFERENCES scopes(id)
);
CREATE TABLE IF NOT EXISTS decisions (
  id TEXT PRIMARY KEY,
  seq INTEGER UNIQUE NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL,
  decider TEXT NOT NULL,
  superseded_by TEXT,
  spec_ref TEXT,
  context TEXT,
  decision TEXT,
  consequences TEXT,
  source TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (superseded_by) REFERENCES decisions(id),
  FOREIGN KEY (spec_ref) REFERENCES specs(id)
);
CREATE TABLE IF NOT EXISTS decision_supersedes (
  superseding_id TEXT NOT NULL,
  superseded_id TEXT NOT NULL,
  partial INTEGER CHECK (partial IN (0, 1)),
  FOREIGN KEY (superseding_id) REFERENCES decisions(id),
  FOREIGN KEY (superseded_id) REFERENCES decisions(id),
  PRIMARY KEY (superseding_id, superseded_id)
);
CREATE TABLE IF NOT EXISTS entity_scopes (
  entity_type TEXT NOT NULL CHECK (entity_type IN ('decision','action','idea','problem','spec','log_entry','status_history','workstream')),
  entity_id TEXT NOT NULL,
  scope_id TEXT NOT NULL,
  FOREIGN KEY (scope_id) REFERENCES scopes(id),
  PRIMARY KEY (entity_type, entity_id, scope_id)
);
CREATE TABLE IF NOT EXISTS free_fields (
  id INTEGER NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('decision','action','idea','problem','spec')),
  entity_id TEXT NOT NULL,
  key TEXT NOT NULL,
  format TEXT NOT NULL CHECK (format IN ('md','json','link','url','text')),
  value TEXT NOT NULL,
  fts_indexed INTEGER CHECK (fts_indexed IN (0, 1)),
  status TEXT CHECK (status IN ('active','deprecated')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS action_dependencies (
  action_id TEXT NOT NULL,
  depends_on TEXT NOT NULL,
  FOREIGN KEY (action_id) REFERENCES actions(id),
  FOREIGN KEY (depends_on) REFERENCES actions(id),
  PRIMARY KEY (action_id, depends_on)
);
CREATE TABLE IF NOT EXISTS problem_actions (
  problem_id TEXT NOT NULL,
  action_id TEXT NOT NULL,
  role TEXT,
  created_at TEXT NOT NULL,
  FOREIGN KEY (problem_id) REFERENCES problems(id),
  FOREIGN KEY (action_id) REFERENCES actions(id),
  PRIMARY KEY (problem_id, action_id)
);
CREATE TABLE IF NOT EXISTS workstreams (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS action_workstreams (
  action_id TEXT NOT NULL,
  workstream_id TEXT NOT NULL,
  FOREIGN KEY (action_id) REFERENCES actions(id),
  FOREIGN KEY (workstream_id) REFERENCES workstreams(id),
  PRIMARY KEY (action_id, workstream_id)
);
CREATE TABLE IF NOT EXISTS ideas (
  id TEXT PRIMARY KEY,
  seq INTEGER UNIQUE NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL,
  package TEXT,
  priority TEXT,
  promoted_to TEXT,
  short_desc TEXT,
  long_desc TEXT,
  abandon_reason TEXT,
  tested TEXT NOT NULL DEFAULT 'not_ready' CHECK (tested IN ('no_need', 'not_ready', 'partially', 'success')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (promoted_to) REFERENCES decisions(id)
);
CREATE TABLE IF NOT EXISTS problems (
  id TEXT PRIMARY KEY,
  seq INTEGER UNIQUE NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL,
  severity TEXT NOT NULL,
  type TEXT NOT NULL,
  linked_spec TEXT,
  linked_act TEXT,
  description TEXT,
  root_cause TEXT,
  fix TEXT,
  wontfix_reason TEXT,
  fast_track INTEGER NOT NULL DEFAULT 0,
  tested TEXT NOT NULL DEFAULT 'not_ready' CHECK (tested IN ('no_need', 'not_ready', 'partially', 'success')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  fixed_at TEXT,
  FOREIGN KEY (linked_spec) REFERENCES specs(id),
  FOREIGN KEY (linked_act) REFERENCES actions(id)
);
CREATE TABLE IF NOT EXISTS specs (
  id TEXT PRIMARY KEY,
  filename TEXT NOT NULL,
  package TEXT,
  version INTEGER NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL,
  supersedes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (supersedes) REFERENCES specs(id)
);
CREATE TABLE IF NOT EXISTS status_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  old_status TEXT,
  new_status TEXT NOT NULL,
  changed_at TEXT NOT NULL,
  changed_by TEXT NOT NULL,
  reason TEXT,
  cascade_trigger TEXT
);
CREATE TABLE IF NOT EXISTS actions (
  id TEXT PRIMARY KEY,
  seq INTEGER UNIQUE NOT NULL,
  title TEXT NOT NULL,
  status TEXT NOT NULL,
  date TEXT NOT NULL,
  owner TEXT,
  priority TEXT,
  source TEXT,
  source_type TEXT CHECK (source_type IN ('decision', 'problem', 'mailbox', 'challenge', 'audit', 'regularization')),
  spec_ref TEXT,
  body TEXT,
  blockers TEXT,
  evidence TEXT,
  defer_reason TEXT,
  cancel_reason TEXT,
  tested TEXT NOT NULL DEFAULT 'not_ready' CHECK (tested IN ('no_need', 'not_ready', 'partially', 'success')),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  FOREIGN KEY (spec_ref) REFERENCES specs(id)
);
CREATE TABLE IF NOT EXISTS log_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL,
  timestamp TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('intro','handoff','question','action','status','reflection','answer','challenge','reminder','objective','decision','idea','pb','spec','architectural','regularization','correction')),
  author TEXT,
  audience TEXT,
  subject TEXT,
  body TEXT,
  ref_id TEXT,
  reply_to INTEGER,
  thread_id INTEGER,
  FOREIGN KEY (reply_to) REFERENCES log_entries(id)
);
CREATE TABLE IF NOT EXISTS writers (
  id TEXT PRIMARY KEY,
  nanoid TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin','agent')),
  responsibility TEXT,
  default_scope TEXT NOT NULL DEFAULT 'workspace',
  display_name TEXT,
  objective TEXT,
  expertise TEXT,
  prohibitions TEXT,
  last_read_log_id INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY (default_scope) REFERENCES scopes(id)
);

-- Cascade control flag table (checked by cascade triggers)
CREATE TABLE IF NOT EXISTS _cascade_disabled (value INTEGER DEFAULT 0);
INSERT OR IGNORE INTO _cascade_disabled VALUES (0);

-- FTS5 full-text search index
CREATE VIRTUAL TABLE IF NOT EXISTS search_index USING fts5(
  entity_type,
  entity_id,
  title,
  body,
  tokenize = 'porter unicode61'
);

-- Indexes (40 total, 3 partial)
CREATE INDEX IF NOT EXISTS idx_decisions_status ON decisions(status);
CREATE INDEX IF NOT EXISTS idx_decisions_date ON decisions(date);
CREATE INDEX IF NOT EXISTS idx_actions_status ON actions(status);
CREATE INDEX IF NOT EXISTS idx_actions_source ON actions(source);
CREATE INDEX IF NOT EXISTS idx_actions_source_type ON actions(source_type);
CREATE INDEX IF NOT EXISTS idx_actions_priority ON actions(priority);
CREATE INDEX IF NOT EXISTS idx_ideas_promoted_to ON ideas(promoted_to);
CREATE INDEX IF NOT EXISTS idx_ideas_status ON ideas(status);
CREATE INDEX IF NOT EXISTS idx_ideas_package ON ideas(package);
CREATE INDEX IF NOT EXISTS idx_problems_linked_act ON problems(linked_act);
CREATE INDEX IF NOT EXISTS idx_problems_severity ON problems(severity);
CREATE INDEX IF NOT EXISTS idx_problems_status ON problems(status);
CREATE INDEX IF NOT EXISTS idx_problems_type ON problems(type);
CREATE INDEX IF NOT EXISTS idx_specs_status ON specs(status);
CREATE INDEX IF NOT EXISTS idx_specs_package ON specs(package);
CREATE INDEX IF NOT EXISTS idx_log_entries_date ON log_entries(date);
CREATE INDEX IF NOT EXISTS idx_log_entries_ref ON log_entries(ref_id);
CREATE INDEX IF NOT EXISTS idx_log_entries_type ON log_entries(type);
CREATE INDEX IF NOT EXISTS idx_log_entries_reply_to ON log_entries(reply_to) WHERE reply_to IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_log_entries_thread ON log_entries(thread_id) WHERE thread_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_status_history_entity ON status_history(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_status_history_cascade ON status_history(cascade_trigger);
CREATE INDEX IF NOT EXISTS idx_problem_actions_action ON problem_actions(action_id);
CREATE INDEX IF NOT EXISTS idx_action_workstreams_workstream ON action_workstreams(workstream_id);
CREATE INDEX IF NOT EXISTS idx_decision_supersedes_superseded ON decision_supersedes(superseded_id);
CREATE INDEX IF NOT EXISTS idx_entity_scopes_scope ON entity_scopes(scope_id);
CREATE INDEX IF NOT EXISTS idx_entity_scopes_entity ON entity_scopes(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_free_fields_entity ON free_fields(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_free_fields_key ON free_fields(key);
CREATE INDEX IF NOT EXISTS idx_workstreams_sort ON workstreams(sort_order);
CREATE INDEX IF NOT EXISTS idx_scopes_parent ON scopes(parent);
CREATE INDEX IF NOT EXISTS idx_scopes_sort ON scopes(sort_order);