-- Governance MCP triggers (generated by @ytrynot/gov-mcp via @ytrynot/qb.createTrigger)
-- 4 cascade triggers + 1 scope inheritance trigger + 1 supersession trigger + 21 FTS5 sync triggers = 27 triggers total

-- ═══ Cascade triggers (AFTER UPDATE) ═══════════════════════════════════════
-- Unidirectional, atomic, impossible to bypass.
-- Cascades can be disabled via a flag table:
--   UPDATE _cascade_disabled SET value = 1;  -- disable
--   UPDATE _cascade_disabled SET value = 0;  -- re-enable

CREATE TRIGGER IF NOT EXISTS trg_act_done_pb
AFTER UPDATE OF status ON actions FOR EACH ROW WHEN NEW.status = 'done' AND OLD.status != 'done'
  AND NOT EXISTS (SELECT 1 FROM _cascade_disabled WHERE value = 1)
BEGIN
INSERT INTO status_history (entity_type, entity_id, old_status, new_status, changed_at, changed_by, reason, cascade_trigger)
  SELECT 'problem', id, status, 'partial', datetime('now'), 'cascade:auto',
         'ACT ' || NEW.id || ' done', NEW.id
  FROM problems p
  WHERE (EXISTS (SELECT 1 FROM problem_actions pa WHERE pa.problem_id = p.id AND pa.action_id = NEW.id)
         OR p.linked_act = NEW.id)
    AND p.status NOT IN ('fixed', 'wontfix', 'partial');

  UPDATE problems
  SET status = 'partial',
      tested = 'partially',
      updated_at = datetime('now')
  WHERE (EXISTS (SELECT 1 FROM problem_actions pa WHERE pa.problem_id = problems.id AND pa.action_id = NEW.id)
         OR linked_act = NEW.id)
    AND status NOT IN ('fixed', 'wontfix', 'partial');
END;

CREATE TRIGGER IF NOT EXISTS trg_act_done_idea
AFTER UPDATE OF status ON actions FOR EACH ROW WHEN NEW.status = 'done' AND OLD.status != 'done'
  AND NEW.source_type = 'decision'
  AND NOT EXISTS (SELECT 1 FROM _cascade_disabled WHERE value = 1)
BEGIN
INSERT INTO status_history (entity_type, entity_id, old_status, new_status, changed_at, changed_by, reason, cascade_trigger)
  SELECT 'idea', id, status, 'implemented', datetime('now'), 'cascade:auto',
         'All ACTs of ' || NEW.source || ' done', NEW.id
  FROM ideas
  WHERE promoted_to = NEW.source
    AND status = 'promoted'
    AND NOT EXISTS (
      SELECT 1 FROM actions a2
      WHERE a2.source = NEW.source
        AND a2.source_type = 'decision'
        AND a2.status NOT IN ('done', 'cancelled')
    );

  UPDATE ideas
  SET status = 'implemented',
      tested = 'partially',
      updated_at = datetime('now')
  WHERE promoted_to = NEW.source
    AND status = 'promoted'
    AND NOT EXISTS (
      SELECT 1 FROM actions a2
      WHERE a2.source = NEW.source
        AND a2.source_type = 'decision'
        AND a2.status NOT IN ('done', 'cancelled')
    );
END;

CREATE TRIGGER IF NOT EXISTS trg_dec_cancelled_idea
AFTER UPDATE OF status ON decisions FOR EACH ROW WHEN NEW.status = 'Cancelled' AND OLD.status != 'Cancelled'
  AND NOT EXISTS (SELECT 1 FROM _cascade_disabled WHERE value = 1)
BEGIN
INSERT INTO status_history (entity_type, entity_id, old_status, new_status, changed_at, changed_by, reason, cascade_trigger)
  SELECT 'idea', id, status, 'abandoned', datetime('now'), 'cascade:auto',
         'DEC ' || NEW.id || ' cancelled', NEW.id
  FROM ideas
  WHERE promoted_to = NEW.id
    AND status NOT IN ('abandoned', 'implemented');

  UPDATE ideas
  SET status = 'abandoned',
      abandon_reason = 'DEC ' || NEW.id || ' cancelled',
      updated_at = datetime('now')
  WHERE promoted_to = NEW.id
    AND status NOT IN ('abandoned', 'implemented');
END;

CREATE TRIGGER IF NOT EXISTS trg_spec_superseded_pb
AFTER UPDATE OF status ON specs FOR EACH ROW WHEN NEW.status = 'superseded' AND OLD.status != 'superseded'
  AND NOT EXISTS (SELECT 1 FROM _cascade_disabled WHERE value = 1)
BEGIN
INSERT INTO status_history (entity_type, entity_id, old_status, new_status, changed_at, changed_by, reason, cascade_trigger)
  SELECT 'problem', id, status, 'open', datetime('now'), 'cascade:auto',
         'SPEC ' || NEW.id || ' superseded', NEW.id
  FROM problems
  WHERE linked_spec = NEW.id
    AND type = 'spec'
    AND status = 'fixed';

  UPDATE problems
  SET status = 'open',
      fix = NULL,
      fixed_at = NULL,
      tested = 'not_ready',
      updated_at = datetime('now')
  WHERE linked_spec = NEW.id
    AND type = 'spec'
    AND status = 'fixed';
END;

-- ═══ Scope inheritance trigger (AFTER INSERT on status_history) ══════════
-- Copies scopes from the parent entity to the new status_history row.
-- Ensures audit trail rows carry the scope context at the moment of change.

CREATE TRIGGER IF NOT EXISTS trg_status_history_scopes
AFTER INSERT ON status_history FOR EACH ROW
BEGIN
INSERT INTO entity_scopes (entity_type, entity_id, scope_id)
  SELECT 'status_history', CAST(NEW.id AS TEXT), es.scope_id
  FROM entity_scopes es
  WHERE es.entity_type = NEW.entity_type AND es.entity_id = NEW.entity_id;
END;

-- ═══ Supersession trigger (AFTER INSERT on decision_supersedes) ════════════
-- Updates decisions.superseded_by on the superseded decision.

CREATE TRIGGER IF NOT EXISTS trg_decision_supersedes_insert
AFTER INSERT ON decision_supersedes FOR EACH ROW
BEGIN
UPDATE decisions
  SET superseded_by = NEW.superseding_id,
      updated_at = datetime('now')
  WHERE id = NEW.superseded_id;
END;

-- ═══ FTS5 sync triggers ═════════════════════════════════════════════════════
-- Pattern: INSERT → index new row. UPDATE → delete old + insert new. DELETE → delete.
-- FTS5 rowid is INTEGER (auto-assigned). Entity IDs are TEXT — filtered by (entity_id, entity_type).

CREATE TRIGGER IF NOT EXISTS trg_decisions_fts_insert
AFTER INSERT ON decisions FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('decision', NEW.id, NEW.title,
          NEW.context || ' ' || NEW.decision || ' ' || NEW.consequences);
END;

CREATE TRIGGER IF NOT EXISTS trg_decisions_fts_update
AFTER UPDATE ON decisions FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'decision';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('decision', NEW.id, NEW.title,
          NEW.context || ' ' || NEW.decision || ' ' || NEW.consequences);
END;

CREATE TRIGGER IF NOT EXISTS trg_decisions_fts_delete
AFTER DELETE ON decisions FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'decision';
END;

CREATE TRIGGER IF NOT EXISTS trg_actions_fts_insert
AFTER INSERT ON actions FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('action', NEW.id, NEW.title,
          NEW.body || ' ' || COALESCE(NEW.evidence, '') || ' ' || COALESCE(NEW.blockers, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_actions_fts_update
AFTER UPDATE ON actions FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'action';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('action', NEW.id, NEW.title,
          NEW.body || ' ' || COALESCE(NEW.evidence, '') || ' ' || COALESCE(NEW.blockers, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_actions_fts_delete
AFTER DELETE ON actions FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'action';
END;

CREATE TRIGGER IF NOT EXISTS trg_ideas_fts_insert
AFTER INSERT ON ideas FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('idea', NEW.id, NEW.title,
          COALESCE(NEW.short_desc, '') || ' ' || COALESCE(NEW.long_desc, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_ideas_fts_update
AFTER UPDATE ON ideas FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'idea';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('idea', NEW.id, NEW.title,
          COALESCE(NEW.short_desc, '') || ' ' || COALESCE(NEW.long_desc, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_ideas_fts_delete
AFTER DELETE ON ideas FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'idea';
END;

CREATE TRIGGER IF NOT EXISTS trg_problems_fts_insert
AFTER INSERT ON problems FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('problem', NEW.id, NEW.title,
          COALESCE(NEW.description, '') || ' ' || COALESCE(NEW.root_cause, '') || ' ' || COALESCE(NEW.fix, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_problems_fts_update
AFTER UPDATE ON problems FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'problem';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('problem', NEW.id, NEW.title,
          COALESCE(NEW.description, '') || ' ' || COALESCE(NEW.root_cause, '') || ' ' || COALESCE(NEW.fix, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_problems_fts_delete
AFTER DELETE ON problems FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'problem';
END;

CREATE TRIGGER IF NOT EXISTS trg_specs_fts_insert
AFTER INSERT ON specs FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('spec', NEW.id, NEW.filename,
          '');
END;

CREATE TRIGGER IF NOT EXISTS trg_specs_fts_update
AFTER UPDATE ON specs FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'spec';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('spec', NEW.id, NEW.filename,
          '');
END;

CREATE TRIGGER IF NOT EXISTS trg_specs_fts_delete
AFTER DELETE ON specs FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = OLD.id AND entity_type = 'spec';
END;

CREATE TRIGGER IF NOT EXISTS trg_log_entries_fts_insert
AFTER INSERT ON log_entries FOR EACH ROW
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('log_entry', CAST(NEW.id AS TEXT), COALESCE(NEW.subject, ''),
          COALESCE(NEW.body, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_log_entries_fts_update
AFTER UPDATE ON log_entries FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = CAST(OLD.id AS TEXT) AND entity_type = 'log_entry';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  VALUES ('log_entry', CAST(NEW.id AS TEXT), COALESCE(NEW.subject, ''),
          COALESCE(NEW.body, ''));
END;

CREATE TRIGGER IF NOT EXISTS trg_log_entries_fts_delete
AFTER DELETE ON log_entries FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = CAST(OLD.id AS TEXT) AND entity_type = 'log_entry';
END;

CREATE TRIGGER IF NOT EXISTS trg_free_fields_fts_insert
AFTER INSERT ON free_fields FOR EACH ROW WHEN NEW.fts_indexed = 1 AND NEW.status = 'active'
BEGIN
INSERT INTO search_index (entity_type, entity_id, title, body)
  SELECT 'free_field', CAST(NEW.id AS TEXT), NEW.key, NEW.value
  WHERE NEW.fts_indexed = 1 AND NEW.status = 'active';
END;

CREATE TRIGGER IF NOT EXISTS trg_free_fields_fts_update
AFTER UPDATE ON free_fields FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = CAST(OLD.id AS TEXT) AND entity_type = 'free_field';
  INSERT INTO search_index (entity_type, entity_id, title, body)
  SELECT 'free_field', CAST(NEW.id AS TEXT), NEW.key, NEW.value
  WHERE NEW.fts_indexed = 1 AND NEW.status = 'active';
END;

CREATE TRIGGER IF NOT EXISTS trg_free_fields_fts_delete
AFTER DELETE ON free_fields FOR EACH ROW
BEGIN
DELETE FROM search_index WHERE entity_id = CAST(OLD.id AS TEXT) AND entity_type = 'free_field';
END;