export { fromDna } from "./fromDna/index.js";
// Type-only re-exports for fromDna<S> type parameter (DnaString, DnaObject, etc.).
// These are erased at runtime — no impact on the JS bundle.
//
// NOTE: tsup/esbuild emits a "imported from external module @ytrynot/dna/core but
// never used" warning for dist/fromDna.js. This is a false positive: fromDna/index.ts
// imports `* as c from '@ytrynot/dna/core'` and uses the classes dynamically (c.DnaString,
// c.DnaObject, ...) for bytecode reconstruction. esbuild cannot track dynamic namespace
// access, so it reports the imports as unused. The build succeeds; the warning is harmless.
export type {
  DnaType,
  DnaSomeType,
  DnaString,
  DnaEmail,
  DnaHttpUrl,
  DnaHostname,
  DnaUUID,
  DnaGuid,
  DnaE164,
  DnaEmoji,
  DnaBase64,
  DnaBase64Url,
  DnaHex,
  DnaNanoId,
  DnaCuid,
  DnaCuid2,
  DnaUlid,
  DnaXid,
  DnaKsuid,
  DnaIpv4,
  DnaIpv6,
  DnaMac,
  DnaCidrv4,
  DnaCidrv6,
  DnaJwt,
  DnaHash,
  DnaEnum,
  DnaLazy,
  DnaInt32,
  DnaInt,
  DnaLiteral,
  DnaPromise,
  DnaTemplateLiteral,
  DnaTmplLiteralMutate,
  DnaTuple,
  DnaUrl,
  DnaStringBool,
  DnaCoerceString,
  DnaCoerceInt,
  DnaCoerceInt32,
  DnaCoerceBoolean,
  DnaCoerceBigInt,
  DnaCoerceDate,
  DnaAny,
  DnaUnknown,
  DnaCustom,
  DnaNever,
  DnaNull,
  DnaUndefined,
  DnaTransform,
  DnaFile,
  DnaSymbol,
  DnaVoid,
  DnaNaN,
  DnaUnion,
  DnaXorUnion,
  DnaIntersection,
  DnaDiscriminatedUnion,
  DnaNot,
  DnaIfThenElse,
  DnaCliUnion,
  DnaObject,
  DnaCodec,
  DnaFunction,
  DnaBigInt,
  DnaBoolean,
  DnaDate,
  DnaPipe,
} from "@ytrynot/dna/core";
