/**
 * Schema definitions for the governance database.
 *
 * 16 tables, 40 indexes (3 partial), FTS5 virtual table.
 * All tables are defined via @ytrynot/qb defTable from DNA row schemas.
 * CHECK constraints use table-level options.checks (DNA introspector does not
 * extract `check` from .meta()). FTS5 uses raw SQL (qb escape hatch).
 */

import { QueryBuilder } from "@ytrynot/qb";
import { CASCADE_DDL } from "./cascade.js";
import { FTS5_DDL } from "./fts5.js";
import { TESTED_STATUSES } from "../../shared/enums.js";
import {
  scopeRowSchema, decisionRowSchema, decisionSupersedesRowSchema, entityScopeRowSchema,
  freeFieldRowSchema, actionDependencyRowSchema, problemActionRowSchema, workstreamRowSchema,
  actionWorkstreamRowSchema, ideaRowSchema, problemRowSchema, specRowSchema,
  statusHistoryRowSchema, actionRowSchema, logEntryRowSchema, writerRowSchema,
} from "../../shared/schemas/rows.js";

/** CHECK constraint for tested column — derived from TESTED_STATUSES enum. */
const TESTED_CHECK = `tested IN (${TESTED_STATUSES.map((v) => `'${v}'`).join(", ")})`;

/** CHECK constraints per table — table-level since DNA introspector doesn't extract `check` from .meta(). */
const decisionSupersedesChecks = ["partial IN (0, 1)"];
const entityScopesChecks = ["entity_type IN ('decision','action','idea','problem','spec','log_entry','status_history','workstream')"];
const freeFieldsChecks = [
  "entity_type IN ('decision','action','idea','problem','spec')",
  "format IN ('md','json','link','url','text')",
  "fts_indexed IN (0, 1)",
  "status IN ('active','deprecated')",
];
const ideasChecks = [TESTED_CHECK];
const problemsChecks = [TESTED_CHECK];
const actionsChecks = [
  "source_type IN ('decision','problem','mailbox','challenge','audit','regularization')",
  TESTED_CHECK,
];
const logEntriesChecks = [
  "type IN ('intro','handoff','question','action','status','reflection','answer','challenge','reminder','objective','decision','idea','pb','spec','architectural','regularization','correction')",
];
const writersChecks = ["role IN ('admin','agent')"];

// ─── Table definitions via qb from DNA schemas ──────────────────────────────

export const tables = {
  scopes: QueryBuilder.defTable("scopes", scopeRowSchema),
  decisions: QueryBuilder.defTable("decisions", decisionRowSchema),
  decision_supersedes: QueryBuilder.defTable(
    "decision_supersedes",
    decisionSupersedesRowSchema,
    { primaryKey: ["superseding_id", "superseded_id"], checks: decisionSupersedesChecks },
  ),
  entity_scopes: QueryBuilder.defTable(
    "entity_scopes",
    entityScopeRowSchema,
    { primaryKey: ["entity_type", "entity_id", "scope_id"], checks: entityScopesChecks },
  ),
  free_fields: QueryBuilder.defTable(
    "free_fields",
    freeFieldRowSchema,
    { primaryKey: ["id"], checks: freeFieldsChecks },
  ),
  action_dependencies: QueryBuilder.defTable(
    "action_dependencies",
    actionDependencyRowSchema,
    { primaryKey: ["action_id", "depends_on"] },
  ),
  problem_actions: QueryBuilder.defTable(
    "problem_actions",
    problemActionRowSchema,
    { primaryKey: ["problem_id", "action_id"] },
  ),
  workstreams: QueryBuilder.defTable("workstreams", workstreamRowSchema),
  action_workstreams: QueryBuilder.defTable(
    "action_workstreams",
    actionWorkstreamRowSchema,
    { primaryKey: ["action_id", "workstream_id"] },
  ),
  ideas: QueryBuilder.defTable("ideas", ideaRowSchema, { checks: ideasChecks }),
  problems: QueryBuilder.defTable("problems", problemRowSchema, { checks: problemsChecks }),
  specs: QueryBuilder.defTable("specs", specRowSchema),
  status_history: QueryBuilder.defTable("status_history", statusHistoryRowSchema),
  actions: QueryBuilder.defTable("actions", actionRowSchema, { checks: actionsChecks }),
  log_entries: QueryBuilder.defTable("log_entries", logEntryRowSchema, { checks: logEntriesChecks }),
  writers: QueryBuilder.defTable("writers", writerRowSchema, { checks: writersChecks }),
} as const;

// FTS5_DDL and CASCADE_DDL are re-exported from their dedicated files.
export { FTS5_DDL } from "./fts5.js";
export { CASCADE_DDL } from "./cascade.js";

// ─── Indexes (generated by qb) ──────────────────────────────────────────────

/** Index definitions — generated via qb.createIndex. */
const indexDefs: ReadonlyArray<() => string> = [
  // decisions
  () => QueryBuilder.table("decisions").createIndex("idx_decisions_status", ["status"]).toSQL(),
  () => QueryBuilder.table("decisions").createIndex("idx_decisions_date", ["date"]).toSQL(),
  // actions
  () => QueryBuilder.table("actions").createIndex("idx_actions_status", ["status"]).toSQL(),
  () => QueryBuilder.table("actions").createIndex("idx_actions_source", ["source"]).toSQL(),
  () => QueryBuilder.table("actions").createIndex("idx_actions_source_type", ["source_type"]).toSQL(),
  () => QueryBuilder.table("actions").createIndex("idx_actions_priority", ["priority"]).toSQL(),
  // ideas
  () => QueryBuilder.table("ideas").createIndex("idx_ideas_promoted_to", ["promoted_to"]).toSQL(),
  () => QueryBuilder.table("ideas").createIndex("idx_ideas_status", ["status"]).toSQL(),
  () => QueryBuilder.table("ideas").createIndex("idx_ideas_package", ["package"]).toSQL(),
  // problems
  () => QueryBuilder.table("problems").createIndex("idx_problems_linked_act", ["linked_act"]).toSQL(),
  () => QueryBuilder.table("problems").createIndex("idx_problems_severity", ["severity"]).toSQL(),
  () => QueryBuilder.table("problems").createIndex("idx_problems_status", ["status"]).toSQL(),
  () => QueryBuilder.table("problems").createIndex("idx_problems_type", ["type"]).toSQL(),
  // specs
  () => QueryBuilder.table("specs").createIndex("idx_specs_status", ["status"]).toSQL(),
  () => QueryBuilder.table("specs").createIndex("idx_specs_package", ["package"]).toSQL(),
  // log_entries (2 partial)
  () => QueryBuilder.table("log_entries").createIndex("idx_log_entries_date", ["date"]).toSQL(),
  () => QueryBuilder.table("log_entries").createIndex("idx_log_entries_ref", ["ref_id"]).toSQL(),
  () => QueryBuilder.table("log_entries").createIndex("idx_log_entries_type", ["type"]).toSQL(),
  () => QueryBuilder.table("log_entries").createIndex("idx_log_entries_reply_to", ["reply_to"], { where: "reply_to IS NOT NULL" }).toSQL(),
  () => QueryBuilder.table("log_entries").createIndex("idx_log_entries_thread", ["thread_id"], { where: "thread_id IS NOT NULL" }).toSQL(),
  // status_history
  () => QueryBuilder.table("status_history").createIndex("idx_status_history_entity", ["entity_type", "entity_id"]).toSQL(),
  () => QueryBuilder.table("status_history").createIndex("idx_status_history_cascade", ["cascade_trigger"]).toSQL(),
  // junction tables
  () => QueryBuilder.table("problem_actions").createIndex("idx_problem_actions_action", ["action_id"]).toSQL(),
  () => QueryBuilder.table("action_workstreams").createIndex("idx_action_workstreams_workstream", ["workstream_id"]).toSQL(),
  () => QueryBuilder.table("decision_supersedes").createIndex("idx_decision_supersedes_superseded", ["superseded_id"]).toSQL(),
  () => QueryBuilder.table("entity_scopes").createIndex("idx_entity_scopes_scope", ["scope_id"]).toSQL(),
  () => QueryBuilder.table("entity_scopes").createIndex("idx_entity_scopes_entity", ["entity_type", "entity_id"]).toSQL(),
  () => QueryBuilder.table("free_fields").createIndex("idx_free_fields_entity", ["entity_type", "entity_id"]).toSQL(),
  () => QueryBuilder.table("free_fields").createIndex("idx_free_fields_key", ["key"]).toSQL(),
  // workstreams
  () => QueryBuilder.table("workstreams").createIndex("idx_workstreams_sort", ["sort_order"]).toSQL(),
  // scopes
  () => QueryBuilder.table("scopes").createIndex("idx_scopes_parent", ["parent"]).toSQL(),
  () => QueryBuilder.table("scopes").createIndex("idx_scopes_sort", ["sort_order"]).toSQL(),
];

/** Generate all index DDL statements via qb. Each statement ends with `;` for db.exec(). */
export function generateIndexDDL(): string[] {
  return indexDefs.map((fn) => `${fn()};`);
}

// ─── Full schema assembly ────────────────────────────────────────────────────

/** Generate the complete schema SQL (tables + CHECK + FTS5 + indexes). */
export function generateSchemaSQL(): string {
  const qbTables = [
    tables.scopes.createTable,
    tables.decisions.createTable,
    tables.decision_supersedes.createTable,
    tables.entity_scopes.createTable,
    tables.free_fields.createTable,
    tables.action_dependencies.createTable,
    tables.problem_actions.createTable,
    tables.workstreams.createTable,
    tables.action_workstreams.createTable,
    tables.ideas.createTable,
    tables.problems.createTable,
    tables.specs.createTable,
    tables.status_history.createTable,
    tables.actions.createTable,
    tables.log_entries.createTable,
    tables.writers.createTable,
  ];

  return [
    "-- Governance MCP schema (generated by @ytrynot/gov-mcp)",
    "-- All tables and indexes generated by @ytrynot/qb from DNA row schemas",
    ...qbTables,
    "",
    CASCADE_DDL,
    "",
    "-- FTS5 full-text search index",
    FTS5_DDL,
    "",
    "-- Indexes (40 total, 3 partial)",
    ...generateIndexDDL(),
  ].join("\n");
}
