import { STEP } from "../shared/stackstep.js";
import type {
	tsJSParentCtx,
	tsJSStepOp,
	tsJSStepString,
	tsLaberlId,
	tsMeta,
	tsStackFrame
} from "../types/index.js";
import { simpleNodeToJs, _err, ERR_UNDEF } from "./utils.js";

export const coerce = (dnaOpt: [[string, number], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx
): tsStackFrame[] => {
	const opt = dnaOpt[0];
	let op, typeChecked;
	switch (opt[0]) {
		case "toString": op = "String(" + _inVarName + ")"; typeChecked = "string"; break;
		case "toNumber": op = "Number(" + _inVarName + ")"; typeChecked = "number"; break;
		case "toBoolean": op = "Boolean(" + _inVarName + ")"; typeChecked = "boolean"; break;
		case "toBigInt": op = "bigint(" + _inVarName + ")"; typeChecked = "bigint"; break;
		default: op = _inVarName;
	}
	return [
		[STEP.BODY, _inVarName + "=" + op + ";"],
		[opt[1], _inVarName, _outVarName, pathVar + "/coerce/" + opt[0], { ...parentCtx, typeChecked }]
	];
}

/**
 * Builder-specific opcodes for DNA schema builder
 * These opcodes are generated by the DNA builder API and are not used by @ytn/schvalid
 * (which produces canonical DNA opcodes directly from JSON Schema).
 *
 * Builder-specific opcodes:
 * - mutate, check, sym: transformation and custom validation functions
 * - codec: bidirectional encode/decode transformation
 * - date, file: specific type validators
 * - default, prefault: value modifiers
 * - wrp: generic wrapper dispatcher for builder
 */

// Generic wrapper handler for builder-generated "wrp" opcode
// Format: ["wrp", [wrptypes, targetId], meta]
// wrptypes: array of [wrptype, value?] where wrptype is "optional", "nullable", "default", "prefault"
// targetId: index of the inner schema in the DNA
// meta: contains default value for default/prefault wrappers
// Note: nullish is represented as optional + nullable in the builder
type tsWrpOpt = [([string, any] | [string])[], number]

export const wrp = (dnaOpt: [tsWrpOpt, tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx
): tsStackFrame[] => {
	const [wrptypes, targetId] = dnaOpt[0];
	const meta = dnaOpt[1];
	const steps: tsStackFrame[] = [];

	// Setup block frame for validator mode (for early break)
	let block = "";
	let break_ = "";
	if (parentCtx.isCond) {
		const idx = labelId();
		block = !parentCtx.failCase ? "wrpB" + idx : "";
		break_ = block ? "break " + block + ";" : parentCtx.failCase;
	}


	if (block) steps.push([STEP.BODY, block + ":{"]);

	// Generate code directly for each wrapper in reverse order (last wins)
	// This matches Zod's behavior where wrappers are applied in reverse declaration order
	// Each wrapper either does early break (with counters/assignments) or continues to validation
	for (let i = wrptypes.length; i--;) {
		const wrapper = wrptypes[i];
		const wrptype = wrapper[0];
		const value = wrapper[1];

		switch (wrptype) {
			case "prefault":
				// prefault: substitute value on undefined, then continue to validation/parsing
				// Same for both validator and parser modes
				steps.push([STEP.BODY, "if(" + _inVarName + "===undefined)" + _inVarName + "=" + value + ";"]);
				break;
			case "default":
				// default: assign on undefined and short-circuit (skip validation/parsing)
				const defaultTest = _inVarName + "===undefined";
				const defaultPreBody = _inVarName + "=" + value + ";";
				const defaultCode = simpleNodeToJs(parentCtx, _inVarName, _outVarName, "", defaultTest, defaultPreBody, "", false);
				steps.push([STEP.BODY, defaultCode]);
				break;
			case "optional":
				// optional: early break on undefined (skip validation/parsing)
				const optionalTest = _inVarName + "===undefined";
				const optionalCode = simpleNodeToJs(parentCtx, _inVarName, _outVarName, "", optionalTest, "", "", true);
				steps.push([STEP.BODY, optionalCode]);
				break;
			case "nullable":
				// nullable: early break on null (skip validation/parsing)
				const nullableTest = _inVarName + "===null";
				const nullableCode = simpleNodeToJs(parentCtx, _inVarName, _outVarName, "", nullableTest, "", "", true);
				steps.push([STEP.BODY, nullableCode]);
				break;
			default:
				throw new Error("Unknown wrapper type: " + wrptype);
		}
	}

	// Generate inner schema call (only reached if no early break)
	const innerCtx = parentCtx.isCond
		? { ...parentCtx, typeChecked: undefined, counter: undefined, not: undefined }
		: { ...parentCtx, typeChecked: undefined };

	steps.push([targetId, _inVarName, _outVarName, pathVar, innerCtx]);


	if (block) steps.push([STEP.BODY, "}"]);

	return steps;
};

// `mutate`: applies a transformation function to the value
export const mutate = (dnaOpt: [string, tsMeta] | [string, string, tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const op = dnaOpt[0][0];
	const idx = labelId();
	const tmp = "mutV" + idx;
	const isCond = parentCtx.isCond;
	let mutation="";
	switch (op) {
		case "trim": mutation = _inVarName + ".trim();"; break;
		case "toUpperCase": mutation = _inVarName + ".toUpperCase();"; break;
		case "toLowerCase": mutation = _inVarName + ".toLowerCase();"; break;
		case "normalize": mutation = _inVarName + ".normalize();"; break;
		case "func": mutation = "(" + dnaOpt[0][1] + ")(" + _inVarName + (isCond ? "":",{issues:errors}") + ")"; break;
		case "assign": mutation = dnaOpt[0][1]; break;
	}

	return mutation ? _inVarName + "=" + mutation + (parentCtx.isCond?";":""):"";
};

// `check`: applies a validation check function
export const check = (dnaOpt: [[string, any?, any?], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const op = dnaOpt[0][0];
	let path, errMsg, test;
	switch (op) {
		case "lowercase":
			// s=>s===s.toLowerCase()
			path = "/lowercase"; errMsg = "String must be in lowercase";
			test = _inVarName + "===" + _inVarName + ".toLowerCase()";
			break;
		case "uppercase":
			// s=>s===s.toUpperCase()
			path = "/uppercase"; errMsg = "String must be in UpperCase";
			test = _inVarName + "===" + _inVarName + ".toUpperCase()";
			break;
		case "endsWith": {
			// s=>s===s.toUpperCase()
			const value = dnaOpt[0][1];
			path = "/endsWith"; errMsg = "String must end with '" + value + "'";
			test = _inVarName + ".endsWith(" + value + ")";
			break;
		}
		case "startsWith": {
			// s=>s===s.toUpperCase()
			const value = dnaOpt[0][1];
			path = "/startsWith"; errMsg = "String must start with '" + value + "'";
			test = _inVarName + ".startsWith(" + value + ")";
			break;
		}
		case "includes": {
			// s=>s===s.toUpperCase()
			const value = dnaOpt[0][1];
			path = "/includes"; errMsg = "String must include '" + value + "'";
			test = _inVarName + ".includes(" + value + ")";
			break;
		}
		case "func": {
			// Custom validation function
			const fnStr = dnaOpt[0][1];
			const fnLength = dnaOpt[0][2];
			path = "/check";
			errMsg = "Custom check failed";
			// Generate function call based on arity
			if (fnLength === 1) {
				test = "(" + fnStr + ")(" + _inVarName + ")";
			} else if (fnLength === 2) {
				test = "(" + fnStr + ")(" + _inVarName + ", ctx)";
			} else {
				test = "(" + fnStr + ")()";
			}
			break;
		}

		default:
			test = "";
			path = "/check";
			errMsg = "Custom check failed";
			break;
	}
	const condErr = _err(parentCtx, _inVarName, pathVar + path, errMsg) + ERR_UNDEF;
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

// `sym`: matches only Symbol values. Zod's `z.symbol()`.
export const sym = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const test = parentCtx.typeChecked === "symbol" ? "" : "typeof " + _inVarName + '==="symbol"';
	const condErr = _err(parentCtx, _inVarName, pathVar + "/symbol", "Symbol is required") + ERR_UNDEF;
	parentCtx.typeChecked = "symbol";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

// `date`: matches a real `Date` instance (Zod's `z.date()`). Excludes invalid
// dates (`new Date("nope")` whose `.getTime()` is NaN), aligning with Zod V4.
export const date = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	// `t===t` is true unless `t` is NaN (NaN is the only value not equal to
	// itself), so `getTime()===getTime()` rejects invalid dates without an
	// extra `Number.isNaN(...)` call.
	const test = _inVarName + " instanceof Date&&" + _inVarName + ".getTime()===" + _inVarName + ".getTime()";
	const condErr = _err(parentCtx, _inVarName, pathVar + "/date", "Date is required") + ERR_UNDEF;
	parentCtx.typeChecked = "date";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

// `file`: matches a `File` instance. `globalThis.File` is available in
// browsers and in Node.js >= 20. Read via `globalThis` so the generated code
// works without an explicit `File` reference in the calling scope.
export const file = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const test = _inVarName + " instanceof globalThis.File";
	const condErr = _err(parentCtx, _inVarName, pathVar + "/file", "File is required") + ERR_UNDEF;
	parentCtx.typeChecked = "file";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

// `instanceOf`: matches an instance of a registered constructor class.
// The constructor name is stored in DNA and retrieved from the registry at runtime.
// Uses simple closure pattern (C captured in preBody for optimal performance).
export const instanceOf = (dnaOpt: [string, tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsStackFrame[] => {
	const constructorName = dnaOpt[0];
	parentCtx.typeChecked = constructorName;
	const idx = labelId();
	const className = "cls"+idx;
	const test = _inVarName + " instanceof "+className;
	const condErr = _err(parentCtx, _inVarName, pathVar + "/instanceOf", "Instance of " + constructorName + " is required") + ERR_UNDEF;

	const steps: tsStackFrame[] = [];
	const isBuiltin = ["Object", "Array", "Function", "String", "Number", "Boolean", "Date", "RegExp", "Error", "Promise", "Map", "Set", "WeakMap", "WeakSet"].includes(constructorName);

	if (!isBuiltin) {
		steps.push([STEP.OUT_CONST, className + "=" + constructorName]);
		steps.push([STEP.OUT_ARG, constructorName]);
	}
	steps.push([STEP.BODY, simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true)]);

	return steps;
};

// `codec`: bidirectional encode/decode transformation
// Format: ["codec", [inSchemaId, outSchemaId, decodeFn, encodeFn], meta]
// decodeFn: function to transform input to output
// encodeFn: function to transform output to input
export const codec = (dnaOpt: [[number, number, string, string], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsStackFrame[] => {
	const [inSchemaId, outSchemaId, decodeFn, encodeFn] = dnaOpt[0];
	const isCond = parentCtx.isCond;

	const steps: tsStackFrame[] = [];

	// Call inSchema for validation
	steps.push([inSchemaId, _inVarName, _outVarName, pathVar, parentCtx]);

	// Apply decode transformation
	const decodeCall = "(" + decodeFn + ")(" + _inVarName + ")";
		steps.push([STEP.BODY, _inVarName + "=" + decodeCall + ";"]);

	// Call outSchema for validation of transformed value
	steps.push([outSchemaId, _inVarName, _outVarName, pathVar, parentCtx]);

	return steps;
};

// Template literal handler
// Format: ["template", [strParts, partIds], meta]
// strParts: array of literals and "\x00" placeholders for schemas
// partIds: array of schema IDs (only for schema positions)
export const template = (dnaOpt: [string[], number[], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx
): tsStackFrame[] => {
	const idx = labelId();
	const strParts = dnaOpt[0];
	const partIds = dnaOpt[1];

	const isCond = parentCtx.isCond;
	const childrenCtx: tsJSParentCtx = { ...parentCtx, isCond, typeChecked: "string" };
	const tmpVar = "tmpLit" + idx;
	const steps: tsStackFrame[] = [];

	// Build capture regex: escape literals, replace schemas with capture groups
	const regexParts: string[] = [];

	for (let i = 0; i < strParts.length; i++) {
		const part = strParts[i];
		if (part === "\x00") regexParts.push("(.+?)");
		else regexParts.push(String(part).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
	}

	// Build regex string
	const regexStr = "^" + regexParts.join("") + "$";
	const regexObj = "new RegExp(" + JSON.stringify(regexStr) + ",'u')";

	// Type check first
	const typeTest = "typeof " + _inVarName + '==="string';
	const typeErr = _err(parentCtx, _inVarName, pathVar + "/template", "Template literal must be a String") + ERR_UNDEF;
	steps.push([STEP.BODY, simpleNodeToJs(parentCtx, _inVarName, _outVarName, typeErr, typeTest, "", "", true)]);

	// Apply regex and capture parts
	const matchTest = _inVarName + ".match(" + regexObj + ")";
	const matchErr = _err(parentCtx, _inVarName, pathVar + "/template", "Template literal does not match pattern") + ERR_UNDEF;
	steps.push([STEP.BODY, simpleNodeToJs(parentCtx, _inVarName, _outVarName, matchErr, matchTest, "", "", true)]);

	// Extract parts for validation
	if (!isCond) {
		steps.push([STEP.LET, "const parts=" + _inVarName + ".match(" + regexObj + ")"]);
	}

	// Validate each captured part with its schema
	for (let i = 0; i < partIds.length; i++) {
		const captureVar = "parts[" + (i + 1) + "]";
		steps.push([partIds[i], captureVar, _outVarName, pathVar + "/template/" + i, childrenCtx]);
	}

	return steps;
};

// `transform`: applies custom schema transformation to the value
export const transform = (dnaOpt: [[string, number], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsStackFrame[] => {
	const [fnStr, fnLength] = dnaOpt[0];
	const isCond = parentCtx.isCond;
	const steps: tsStackFrame[] = [];

	// Apply transform
	const ctxArg = !isCond && fnLength > 1 ? ",{issues:errors}" : "";
	const mutation = "(" + fnStr + ")(" + _inVarName + ctxArg + ")";
	steps.push([STEP.BODY, _inVarName + "=" + mutation + (parentCtx.isCond ? ";" : "")]);

	return steps;
};

// `preprocess`: transform function applied before validation
// Format: ["preprocess", [schemaId, fnStr, fnLength], meta]
// transformFn: function to transform input before schema validation
export const preprocess = (dnaOpt: [[number, string, number], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsStackFrame[] => {
	const [schemaId, fnStr, fnLength] = dnaOpt[0];
	const isCond = parentCtx.isCond;

	const steps: tsStackFrame[] = [];

	// Apply preprocess transformation
	const ctxArg = !isCond && fnLength > 1 ? ",{issues:errors}" : "";
	const preprocessCall = "(" + fnStr + ")(" + _inVarName + ctxArg + ")";
	steps.push([STEP.BODY, _inVarName + "=" + preprocessCall + ";"]);

	// Call schema for validation of transformed value
	steps.push([schemaId, _inVarName, _outVarName, pathVar, parentCtx]);

	return steps;
};

// `pipe`: chain input schema → transform → output schema
// Format: ["pipe", [inSchemaId, outSchemaId, transformFn, arity], meta]
// Similar to codec but for one-way transformation (decode only)
export const pipe = (dnaOpt: [[number, number, string, number], tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsStackFrame[] => {
	const [inSchemaId, outSchemaId, transformFn, fnLength] = dnaOpt[0];
	const isCond = parentCtx.isCond;

	const steps: tsStackFrame[] = [];

	// Call inSchema for validation
	steps.push([inSchemaId, _inVarName, _outVarName, pathVar, parentCtx]);

	// Apply transform
	const ctxArg = !isCond && fnLength > 1 ? ",{issues:errors}" : "";
	const transformCall = "(" + transformFn + ")(" + _inVarName + ctxArg + ")";
	steps.push([STEP.BODY, _inVarName + "=" + transformCall + ";"]);

	// Call outSchema for validation of transformed value
	steps.push([outSchemaId, _inVarName, _outVarName, pathVar, parentCtx]);

	return steps;
};

const functionHandler = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const test = "typeof " + _inVarName + '==="function';
	const condErr = _err(parentCtx, _inVarName, pathVar + "/function", "Function is required") + ERR_UNDEF;
	parentCtx.typeChecked = "function";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

const voidHandler = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const test = _inVarName + "===void 0";
	const condErr = _err(parentCtx, _inVarName, pathVar + "/void", "Undefined is required") + ERR_UNDEF;
	parentCtx.typeChecked = "undefined";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

export const promise = (dnaOpt: [tsMeta], _inVarName: string, _outVarName: string, pathVar: string, labelId: tsLaberlId, parentCtx: tsJSParentCtx): tsJSStepString => {
	const test = _inVarName + " instanceof Promise";
	const condErr = _err(parentCtx, _inVarName, pathVar + "/promise", "Promise is required") + ERR_UNDEF;
	parentCtx.typeChecked = "promise";
	return simpleNodeToJs(parentCtx, _inVarName, _outVarName, condErr, test, "", "", true);
};

export {
	functionHandler as function,
	voidHandler as void,
};
