import { dna } from "@ytrynot/dna";
import type { DnaCliUnion, DnaSomeType } from "@ytrynot/dna/core";
import type { $Flatten } from "@ytrynot/shared/types/structural.type.js";
import { parseArgs as nodeParseArgs } from "node:util";
import type { $RouteIdProp } from "./routeId.js";
import type {
  IFlagMap,
  OParseArgsConfig,
  OPositionalMeta,
} from "./types/contract.types.js";

declare const parseArgs: typeof nodeParseArgs;

/**
 * Builds the layer 0-1 pipeline:
 *
 *   dna.preprocess((argv) => ({ argv }),
 *     dna.object({ argv, _parseArgsConfig, _positionalMeta, _flagMap })
 *     .transform(parseArgs + flag routing + remap → flat, { parseArgs })
 *     .pipe(cliUnion)
 *     .transform(extract \x00ID → { route, payload })
 *   )
 *
 * Only 1 external: parseArgs. The 3 config objects are DNA defaults,
 * inlined in the generated bytecode by toJS.
 */
export function buildPipeline<
  S extends readonly DnaSomeType<Record<string, unknown> & $RouteIdProp>[],
>(
  cliUnion: DnaCliUnion<S>,
  parseArgsConfig: OParseArgsConfig,
  positionalMeta: OPositionalMeta[],
  flagMap: IFlagMap,
) {
  const inputSchema = dna.object({
    argv: dna.array(dna.string()),
    _parseArgsConfig: dna.any().default(parseArgsConfig),
    _positionalMeta: dna.any().default(positionalMeta),
    _flagMap: dna.any().default(flagMap),
  });

  const parseStep = inputSchema.transform(
    (v) => {
      const raw = parseArgs({ args: v.argv, ...v._parseArgsConfig });
      const flat = { ...raw.values };
      let pos = raw.positionals;
      for (const flagName in v._flagMap) {
        if (flat[flagName]) {
          pos = [v._flagMap[flagName], ...pos];
          break;
        }
      }
      let pi = 0;
      for (const { name, variadic } of v._positionalMeta) {
        if (variadic) {
          flat[name] = pos.slice(pi);
          pi = pos.length;
        } else {
          if (pi < pos.length) flat[name] = pos[pi];
          pi++;
        }
      }
      return flat;
    },
    { parseArgs: "parseArgs" },
  );

  // type ttp = dna.infer<typeof parseStep>;
  const routed = parseStep.pipe(cliUnion);
  // type ttr = dna.infer<typeof routed>;

  // Guard: if cliUnion rejected, v is undefined — return early to avoid TypeError.
  // The pipe handler in parser mode does NOT check errors.length between steps
  // (unlike chkSeq), so this transform runs even when cliUnion pushes errors and
  // sets its output to undefined. The parser returns {success:false, errors} at
  // the end, so this return value is discarded — the guard only prevents a
  // TypeError on `v["\x00ID"]` when v is undefined.
  // ROUTE_ID_KEY is "\x00ID" — inlined as literal because DNA serializes
  // the transform body to bytecode; external constants are not accessible
  const extractStep = routed.transform((v) => {
    if (v && typeof v === "object") {

      // if (v && typeof v === "object" && "\x00ID" in v) {
      // CAST: \x00ID is dna.string().default(routeId), always string at runtime
      const route = v["\x00ID"];
      // CAST: v is an object payload from cliUnion, has index signature at runtime
      const { "\x00ID": _, ...cleanPayload } = v;
      // CAST: $Flatten forces TS to resolve the destructured rest object as a flat type
      return { route, payload: cleanPayload as $Flatten<typeof cleanPayload> };
    }
    return { route: "" as const, payload: {} };
  });

  // preprocess wraps argv → { argv } so the object schema can apply defaults.
  // No externals on the preprocessor itself — parseArgs is on the .transform().
  return dna.preprocess(
    (argv: unknown) => ({ argv: argv as string[] }),
    extractStep,
  );
}
